- name: Luisky's Fedora Workstation
  hosts: localhost
  tasks:
    
    # DNF config and packages
    - name: DNF keeps only 2 versions of the same package 
      become: yes
      args:
        warn: false
      command: dnf config-manager --setopt=installonly_limit=2 --save
    
    - name: Import the RPM Fusion free repo GPG key
      become: yes
      rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    
    - name: Import the RPM Fusion nonfree repo GPG key
      become: yes
      rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    
    - name: Import the RPM Fusion free repo
      become: yes
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'
    
    - name: Import the RPM Fusion nonfree repo
      become: yes
      dnf:
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'
    
    - name: Import the Google Chrome GPG key
      become: yes
      rpm_key:
        state: present
        key: https://dl.google.com/linux/linux_signing_key.pub
    
    - name: Import the Google Chrome repo
      become: yes
      dnf:
        name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        state: present
    
    - name: Import VS Code key
      become: yes
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
    
    - name: Import VS Code repos
      become: yes
      command: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'

    - name: Upgrade all packages
      become: yes
      dnf:
        name: "*"
        state: latest 
    
    - name: Install useful packages
      become: yes
      dnf:
        name:
          - code
          - vim-enhanced
          - deja-dup
          - gnome-tweaks
          - cockpit
          - fish
          - thunderbird
          - rclone
          - nextcloud-client
          - nextcloud-client-nautilus
          - tilix
          - tilix-nautilus
          - make
          - automake
          - gcc-c++
          - kernel-devel
          - cmake
          - meson
          - python3-psutil
          - python3-pygments
          - conda
        state: present



# Git config and config files
    - name: Configure git email
      command: git config --global user.email "luis.thomas2005@gmail.com"
    
    - name: Configure git name
      command: git config --global user.name "Luis Thomas"
    
    - name: Download gdb dashboard
      command: wget -P ~ https://git.io/.gdbinit
    
    - name: Import my vim config
      command: wget -O /home/{{ ansible_user }}/.vimrc https://gist.githubusercontent.com/Luisky/e06a19469454ecb6afe0756d33a5fa1a/raw/406b97139e86ba4239ce25eaf701e860ae9bf137/.vimrc



    # Dconf and gnome configuration
    - name: Configure available keyboard layouts in Gnome
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'fr')]"
        state: present
    
    - name: Configure Dark Theme
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        state: present
    
    - name: Show weekday in gnome-shell clock
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: "'true'"
        state: present
    
    - name: Allow volume above 100%
      dconf:
        key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
        value: "'true'"
        state: present
    
    - name: Show Battery percentage
      dconf:
        key: "/org/gnome/desktop/interface/show-battery-percentage"
        value: "'true'"
        state: present
    
    - name: Change mouse acceleration profile to Flat
      dconf:
        key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
        value: "'flat'"
        state: present



    # Flatpak and Flathub apps
    - name: Import Flathub Repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    
    - name: Install Flatseal
      flatpak:
        name: com.github.tchx84.Flatseal
        state: present
    
    - name: Install Spotify
      flatpak:
        name: com.spotify.Client
        state: present
    
    - name: Install draw.io
      flatpak:
        name: com.jgraph.drawio.desktop
        state: present
    
    - name: Install Mendeley
      flatpak:
        name: com.elsevier.MendeleyDesktop
        state: present
    
    - name: Install KeePassXC
      flatpak:
        name: org.keepassxc.KeePassXC
        state: present
    
    - name: Install Foliate
      flatpak:
        name: com.github.johnfactotum.Foliate
        state: present

    - name: Install Telegram
      flatpak:
        name: org.telegram.desktop
        state: present



    # JetBrains toobox install (the link may be old and needs updating)
    - name: Donwload jetbrains-toolbox archive
      get_url:
        url: https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.19.7784.tar.gz
        dest: "{{ playbook_dir }}"
    
    - name: Decompress jetbrains-toolbox
      unarchive:
        src: jetbrains-toolbox-1.18.7609.tar.gz
        dest: "{{ playbook_dir }}"
    
    - name: Run jetbrains-toolbox
      command: ./jetbrains-toolbox-1.18.7609/jetbrains-toolbox



    # Rustup install
    - name: Download rustup-init.sh
      get_url:
        url: https://sh.rustup.rs
        dest: "{{ playbook_dir }}"
    
    - name: Run rustup-init.sh
      command: sh rustup-init.sh -y



    # Enable cockpit service
    - name: Enable service cockpit and ensure it is not masked
      ansible.builtin.systemd:
        name: cockpit.socket
        enabled: yes
        state: started


    
    - debug:
        msg: If you see this -> poor yourself a drink, Good Job Mate !