- hosts: localhost
  tasks:
    - name: DNF keeps only 2 versions of the same package 
      become: yes
      args:
        warn: false
      command: dnf config-manager --setopt=installonly_limit=2 --save
    - name: Install Backups, Tilix, Geary, Evolution, Tweaks, Extensions, Appindicator, Fish, Zsh, Make, Automake, GCC-C++, Kernel Headers, CMake, Meson, Mumble, Telegram, Julia
      become: yes
      package:
        name: 
          - deja-dup
          - tilix
          - geary
          - evolution
          - gnome-tweaks
          - gnome-extensions-app
          - gnome-shell-extension-appindicator
          - fish
          - zsh
          - make
          - automake
          - gcc-c++
          - kernel-devel
          - cmake
          - meson
          - mumble
          - telegram-desktop
          - julia
        state: present
    - name: Configure git email
      command:  git config --global user.email "luis.thomas2005@gmail.com"
    - name: Configure git name
      command:  git config --global user.name "Luis Thomas"
    - name: install the RPM Fusion free repo GPG key
      become: yes
      rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-free-fedora-2020
    - name: install the RPM Fusion nonfree repo GPG key
      become: yes
      rpm_key:
        state: present
        key: https://rpmfusion.org/keys?action=AttachFile&do=get&target=RPM-GPG-KEY-rpmfusion-nonfree-fedora-2020
    - name: install the RPM Fusion free repo
      become: yes
      dnf:
        name: "https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'
    - name: install the RPM Fusion nonfree repo
      become: yes
      dnf:
        name: "https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
        state: present
      when: ansible_distribution == 'Fedora'
    - name: Import VS Code key
      become: yes
      rpm_key:
        state: present
        key: https://packages.microsoft.com/keys/microsoft.asc
    - name: Add VS Code repos
      become: yes
      command: sh -c 'echo -e "[code]\nname=Visual Studio Code\nbaseurl=https://packages.microsoft.com/yumrepos/vscode\nenabled=1\ngpgcheck=1\ngpgkey=https://packages.microsoft.com/keys/microsoft.asc" > /etc/yum.repos.d/vscode.repo'
    - name: DNF check-update
      become: yes
      args:
        warn: false
      command: dnf check-update
    - name: Install code
      become: yes
      package:
        name: code
        state: present
    - name: Install code-insiders
      become: yes
      package:
        name: code-insiders
        state: present
    - name: Install GRML zsh config file
      command: wget -O /home/{{ ansible_user }}/.zshrc https://git.grml.org/f/grml-etc-core/etc/zsh/zshrc
    - name: Install GRML zsh user config
      command: wget -O /home/{{ ansible_user }}/.zshrc.local https://git.grml.org/f/grml-etc-core/etc/skel/.zshrc
    - name: Install Flathub Repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo