- hosts: localhost
  tasks:
    - name: install the rpmfusion repo packages
      dnf:
        name: "{{ item }}"
        state: present
        become: yes
      with_items:
        - http://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm
        - http://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ hostvars[inventory_hostname].ansible_distribution_major_version }}.noarch.rpm