- name: Testing file
  hosts: localhost
  tasks:
    - name: install the NordVPN GPG key
      become: yes
      rpm_key:
        state: present
        key: https://repo.nordvpn.com/gpg/nordvpn_public.asc
    - name: install nordvpn command line tool (don't judge)
      become: yes
      dnf:
        name: "https://repo.nordvpn.com/yum/nordvpn/centos/noarch/Packages/n/nordvpn-release-1.0.0-1.noarch.rpm"
        state: present
    - name: Google Chrome 
      become: yes
      dnf:
        name: "https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm"
        state: present