- hosts: localhost
  tasks:
    - name: Install Flathub Repository
      become: yes
      command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
    - name: Install Flatseal
      flatpak:
        name: flatseal
        state: present
    - name: Install Spotify
      flatpak:
        name: spotify
        state: present
    - name: Install NordPass
      flatpak:
        name: nordpass
        state: present
    - name: Install Discord
      flatpak:
        name: discord
        state: present
    - name: Install Slack
      flatpak:
        name: slack
        state: present