- hosts: localhost
  tasks:
    - name: download jetbrains-toolbox
      command: wget https://download.jetbrains.com/toolbox/jetbrains-toolbox-1.18.7609.tar.gz
    - name: untar jetbrains-toolbox
      command: tar xf jetbrains-toolbox-1.18.7609.tar.gz
    - name: run jetbrains-toolbox
      command: ./jetbrains-toolbox-1.18.7609/jetbrains-toolbox