- hosts: localhost
  tasks:
    - name: Configure available keyboard layouts in Gnome
      community.general.dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'fr')]"
        state: present