- hosts: localhost
  tasks:
    - name: download rustup-init.sh
      get_url:
        url: https://sh.rustup.rs
        dest: "{{ playbook_dir }}"
    - name: execute rustup-init.sh
      command: sh rustup-init.sh -y