- hosts: localhost
  tasks:
    - name: Install psutil
      become: yes
      package:
        name: python3-psutil
    - name: Configure available keyboard layouts in Gnome
      dconf:
        key: "/org/gnome/desktop/input-sources/sources"
        value: "[('xkb', 'us'), ('xkb', 'fr')]"
        state: present
    - name: Configure Super-Tab for switching between applications
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications"
        value: "['<Super>Tab']"
        state: present
    - name: Configure Shift-Super-Tab for switching back between applications
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
        value: "['<Shift><Super>Tab']"
        state: present
    - name: Configure Alt-Tab for switching between windows
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows"
        value: "['<Alt>Tab']"
        state: present
    - name: Configure Alt-Tab for switching back between windows
      dconf:
        key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
        value: "['<Shift><Alt>Tab']"
        state: present
    - name: Configure Dark Theme
      dconf:
        key: "/org/gnome/desktop/interface/gtk-theme"
        value: "'Adwaita-dark'"
        state: present
    - name: Show weekday in gnome-shell clock
      dconf:
        key: "/org/gnome/desktop/interface/clock-show-weekday"
        value: true
        state: present
    - name: Change mouse acceleration profile to Flat
      dconf:
        key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
        value: "'flat'"
        state: present